[versions]
activity-compose = "1.12.2"
android-gradle-plugin = "8.13.2"
coil-compose = "2.7.0"
compose-bom = "2025.12.01"
compose-ui = "1.10.0"
core-ktx = "1.17.0"
core-testing = "2.2.0"
espresso-core = "3.7.0"
hilt-android = "2.57.2"
hilt-navigation-compose = "1.3.0"
junit = "4.13.2"
junit-ktx = "1.3.0"
kotlin-android-plugin = "2.2.21"
kotlinx-coroutines-test = "1.10.2"
kotlinx-serialization-json = "1.9.0"
ksp = "2.3.0"
lifecycle-runtime-ktx = "2.10.0"
logging-interceptor = "5.3.2"
material-icons-extended-android = "1.7.8"
material3 = "1.4.0"
mockito-inline = "5.2.0"
mockito-kotlin = "6.1.0"
navigation-compose = "2.9.6"
retrofit = "3.0.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-android" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-ktx" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
material-icons-extended-android = { module = "androidx.compose.material:material-icons-extended-android", version.ref = "material-icons-extended-android" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-inline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-kotlinx-serialization-converter = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose-ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android-plugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-android-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-android-plugin" }